<form action="/html/admin/login" method="post">
    <div class="form-group">
        <label for="name">Имя</label>
        <input type="text" name="name" class="form-control" >
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" name="password" class="form-control">
    </div>
    <?php if($this->error): ?>
        <div class="alert alert-danger" role="alert">
            <?=$this->error;?>
        </div>
    <?php endif; ?>
    <button type="submit" class="btn btn-primary">Войти</button>
</form>

